#!/usr/bin/env node
// 1) Re-compresses each hero image at q=75 (extra ~25% smaller).
// 2) Generates a tiny 16px-wide blurred base64 thumbnail per hero,
//    writes them to lib/hero-blurs.ts as a typed export.

import sharp from "sharp";
import { readFile, writeFile, rename, stat } from "node:fs/promises";

const heroes = [
  { key: "home", path: "public/images/hero-tomsk.jpg" },
  { key: "led", path: "public/images/led/hero-led-tomsk.jpg" },
  { key: "design", path: "public/images/design-portfolio.jpg" },
  { key: "exhibition", path: "public/images/exhibition.jpg" },
  { key: "production", path: "public/images/production-workshop.jpg" },
  { key: "outdoor", path: "public/images/outdoor-mix.jpg" },
  { key: "print", path: "public/images/production.jpg" },
  { key: "russifikaciya", path: "public/images/blog/russifikaciya-hero.jpg" },
];

const blurs = {};
let totalBefore = 0;
let totalAfter = 0;

for (const h of heroes) {
  try {
    const statBefore = await stat(h.path);
    totalBefore += statBefore.size;

    const input = await readFile(h.path);

    // 1) recompress at q=75, max width 1920
    const compressed = await sharp(input)
      .resize(1920, null, { withoutEnlargement: true })
      .jpeg({ quality: 75, progressive: true, mozjpeg: true })
      .toBuffer();

    if (compressed.length < statBefore.size * 0.95) {
      await writeFile(h.path + ".tmp", compressed);
      await rename(h.path + ".tmp", h.path);
      totalAfter += compressed.length;
      console.log(
        `OK ${h.path}: ${Math.round(statBefore.size / 1024)} → ${Math.round(
          compressed.length / 1024,
        )} КБ`,
      );
    } else {
      totalAfter += statBefore.size;
      console.log(`SKIP ${h.path}: already tight`);
    }

    // 2) blur placeholder (16px wide blurred, base64)
    const blur = await sharp(input)
      .resize(16, null, { withoutEnlargement: true })
      .blur(2)
      .jpeg({ quality: 50 })
      .toBuffer();
    blurs[h.key] = `data:image/jpeg;base64,${blur.toString("base64")}`;
  } catch (e) {
    console.warn(`ERR ${h.path}: ${e.message}`);
  }
}

const tsContent = `// Generated by scripts/optimize-heroes.mjs — do not edit by hand.
export const HERO_BLURS = ${JSON.stringify(blurs, null, 2)} as const;

export type HeroKey = keyof typeof HERO_BLURS;
`;

await writeFile("lib/hero-blurs.ts", tsContent, "utf-8");

console.log("\n=== Summary ===");
console.log(`Heroes processed: ${heroes.length}`);
console.log(`Total before: ${(totalBefore / 1024).toFixed(0)} КБ`);
console.log(`Total after:  ${(totalAfter / 1024).toFixed(0)} КБ`);
console.log(`Saved: ${((totalBefore - totalAfter) / 1024).toFixed(0)} КБ`);
console.log(`Wrote lib/hero-blurs.ts with ${Object.keys(blurs).length} blurs`);
